// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGP48YVQ_PG7ZX44lbApMx6OPFUaPGWk',
    appId: '1:737224928227:web:b287a84e6a14968b278ed6',
    messagingSenderId: '737224928227',
    projectId: 'project-a8d49',
    authDomain: 'project-a8d49.firebaseapp.com',
    storageBucket: 'project-a8d49.appspot.com',
    measurementId: 'G-DB9B6KG2GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeXdoxScoGUygOFpNS1FVsFsIDQPAj8v8',
    appId: '1:737224928227:android:8feb418d388c0bc3278ed6',
    messagingSenderId: '737224928227',
    projectId: 'project-a8d49',
    storageBucket: 'project-a8d49.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMGP48YVQ_PG7ZX44lbApMx6OPFUaPGWk',
    appId: '1:737224928227:web:f6ff06ada1f12146278ed6',
    messagingSenderId: '737224928227',
    projectId: 'project-a8d49',
    authDomain: 'project-a8d49.firebaseapp.com',
    storageBucket: 'project-a8d49.appspot.com',
    measurementId: 'G-1P6M9N7GVP',
  );
}
